### ISSUE TITLE
Performance degradation / Services stuck on downloading task file after upgrade to stable89

### ISSUE THREAD

**Issue by kam193** [CybercentreCanada/assemblyline#167] opened 2024-01-13 12:40 UTC
**Describe the bug**
I hope it's my last report for a while. ;) For a last few days, I've been fighting against performance issues preventing my AL instance from finishing any submission. It started after I did two things: added new big YARA rules set and upgraded AssemblyLine to stable89.

tl;dr: After upgrading to stable89 on my Docker compose setup, task services after processing some tasks suddenly stuck in `task_handler` on `Downloading file: [...]`, or stuck immediately after starting on, waiting for the first named pipe to be ready.

The first thing I've observed were just long-standing not-finished submissions. After a few months of running this instance, my experience was that even when there is a peak in submissions, they should be processed in 10-20 minutes, the worst case by big pick. Now, there was not a single submission processed for hours. I've started to dig in, the improvement when downgrading to 88 was visible from the first try. However, I use not a huge, but rather hobby-oriented setup (docker compose including Elastic&minio, 12 vCPU, 40 GB RAM - it's not the smallest too). As so, I tried to find what's going on & tweak the configuration, suspecting my limited setup being the root cause. I observed services being set up but not getting any or stopped getting tasks, without any error log; there were some OOM-kills, but just the `usual` (like `floss`, which probably liked to be Chrome ;)). 

I tried multiple configuration changes:
* tweaking service server's Gunicorn capacity (workers, threads, timeout, max requests, backlog size...),
* tweaking memory & cpu allocation as well as shrinking & growing settings up and down,
* tracking OOM-kills and scaler behavior,
* tracking service server behavior,
* configuring `TASK_COMPLETE_LIMIT` and scaling down `TASK_REQUEST_TIMEOUT`,
* some tweaking `max_inflight` settings,
* tracking Redis clients connections,
* verifying ElasticSearch configuration and working,
* scaling up dispatcher instances 1->2,
* restarting the whole composer,
* probably something else.

However, anything I did, it ended in the same state, sometimes with small improvements or degradation. Finally, I discovered that the repeating behavior is:

* oft visible in Dashboard that task services have retries,
* unusually often task services being reported in Dashboard as not taking any tasks, although the queue was very high,
* scaler replacing services constantly every few minutes,
* in logs, the only clue I found is that after processing some number of files, services stop in `task_handler` on `Downloading file: [...]`, and later are replaced by scaler. Sometimes newly started services were stuck on `Waiting for receive task named pipe to be ready...`.
* services with low queues seemed not be very touched by the problem, they were able to process their tasks;
* restarting service server, dispatcher, or the whole setup were helping for a while - once even processed two whole submissions! :smile: But soon no file was fully processed, and queues in most-loaded services were only growing, with 0 or a few files processed.

Unfortunately, I wasn't able to find any clear clue what is causing that.

Later, the issue with processing caused the submission queue to grow up, which then caused the dispatcher and Redis to eat entire memory and be killed a few times. But handling this (more memory for Redis, scaling up the dispatcher and scaling down the number of in-flight submissions) didn't help with the main issue.

However, downgrading to `stable88` helps every time. I tried it a few times, and as soon as I downgraded, services are not being stuck and keep working for long times. Queues are initially high due to a lot of awaiting submissions, but soon AL is catching up, balancing the load quite well.

The issue touches both custom and standard services (e.g. Characterize)

Have you seen such a behavior? Do you have any ideas?

**To Reproduce**
I'm afraid it may not be the easiest one to reproduce.

1. Have a Docker compose-based setup. Resources rather limited compared to the number of services, so by default almost all services have no instance.
2. Install Assemblyline `stable89`.
3. Load submissions. In my cases, they are always archives with multiple files inside, so a few hundreds submissions creates up to a few thousands files. When I first saw the issue, there were about 200 submissions in the queue, but normally, I have 10-20 at once, sometimes it peaks up to 100, but rarely.
4. After a few minutes, observe submissions not being processed any more, retries visible in Dashboard, scaler playing with services and so on. Dispatcher metric about files processed in the last minute should stay at 0, eventually 1-2.
5. Downgrade AL to `stable88`, restart the Compose.
6. Observe that even after a few minutes, AL is going well with the load, files should be processed constantly, and services are long-living. There should be much less retries.

**Expected behavior**
After upgrade to `stable89`, the AL should work no worse than earlier.

**Screenshots**

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: 4.4.0.88/89
 - Setup with Docker compose, ElasticSearch 7.17.4, Redis 7.0.12, minio `RELEASE.2023-11-15T20-43-25Z`

**Additional context**
I think I learned something about the internals of AL debugging this :grinning:

**Comment by cccs-rs** [comment] 2024-01-15 13:56
Interesting, we haven't noticed anything in our productions systems running Kubernetes but I wonder if the changes in this [commit](https://github.com/CybercentreCanada/assemblyline-base/commit/3f855bc3ae052d543c042be89ffcaeaee2dc028c#diff-4b205347cbc43fdf3267616e83e2eb8bcc61d25f2247d5d34baf2d865eee18e5) with regards to S3 optimizations mentioned in the release can explain the cause.

Although based on the fact that this doesn't happen immediately on a clean system, I wonder if it has anything to do with the caching bug fix mentioned [here](https://github.com/CybercentreCanada/assemblyline-core/commit/74755b550a6bd00cba0c6c48d52fcd4063658a3d) (also included in the stable89 release)

**Comment by cccs-sgaron** [comment] 2024-01-15 16:45
For having pushed both those changes, I don't think the s3 change should really matter because it just uses a lock to create the session. This only happens when filestore object are created and most of our components just always reuse the same filestore object and it's being initialized once. Also the patch from download should actually makes things faster, not slower, has the exists function to the filestore object is not called anymore saving between 2-8 ms per download call. 

The caching fix patch on the other hand will create more CPU usage when a file is seen mulitple times as it will refresh its classification, stats and expiry_ts. Could that added processing time, cause the system from tipping over because there such a small amount of resources? maybe? Are there a lot of files that you are submitting that are duplicates?

**Comment by kam193** [comment] 2024-01-16 23:11
Thanks for your answers! An update while I'm still trying to catch the cause:

  - Yes, I have possibly a lot of duplicated files (I play with analyzing Python packages, so there is a part of repeating files).
  - However, it doesn't look like resources are the problem: I haven't observed troubles with CPU usage, it can be even lower compared to working system.
  - I took your idea about duplicates, and managed to create a minimal setup where I easily trigger a freeze on the Extract service in v89, and (almost) never in v88. There is also a second service running, which seems not to be hanging (I don't have a good theory why yet, but it's a much simpler service - but maybe because it's never uploading any file :thinking: ). The setup is just a minimal AL without scaler, so it doesn't try to restart service after task timeout.
  - My test submission file is just an archive with many small files (incl. duplicates) and some nested archives ([test.tar.gz](https://github.com/CybercentreCanada/assemblyline/files/13956471/test.tar.gz)). After initial feeding AL with it a little more, now it's enough to upload it 5 times to have almost 100% chances to trigger the issue.
  - Interestingly, the issue I am able to reproduce on dev setup is a little different from the reported: I see a freeze mostly on uploading results (`post http://al_service_server:5003/api/v1/task/`), sometimes on downloading. My working theory is that it's the same issue, but a crafted input file and/or different workload causes it more often in a different place.
  - Very interestingly too, I managed to make the freeze once on v88. I am not sure if it's related, or I was just inpatient. 
  - As you can assume from above, I isolated the issue to the Service Server - mix of Service Server in v88, and the rest of core in v89 seems to work well.
  - According to my current findings, the issue occurs on the Service Server side and causes HTTP request to be hanging indefinitely.
  - On the client side, it can be mitigated with request timeout and retry; The `TaskHandler` from `assemblyline_service_client/task_handler.py` has a retry mechanism, but no default timeout - it's set only on some requests. On the server side, it is unclear to me why the connection isn't timeouting - working theory: gevent isn't dead, so Gunicorn doesn't see timeout...
  - I observe some reconnections to Elasticsearch caused by `ConflictError(409, 'version_conflict_engine_exception', `, but so far, it looks like they are handled well.
  - After some heavy log-based debugging, I managed to most probably isolate the issue to [those lines](https://github.com/CybercentreCanada/assemblyline-core/blob/74755b550a6bd00cba0c6c48d52fcd4063658a3d/assemblyline_core/tasking_client.py#L345-L347). My current state is that sometimes part of threads running in executor from L364 stops working on a call to `self.datastore.save_or_freshen_file`.
  - So far, looks like the communication with Elasticsearch (what was my first candidate for the cause because of reconnections) works alright, so maybe it is somewhere else.
  - And even if I'm able to (most probably) see which gunicorn worker is frozen, it looks like technically gevent was still working - PyStack still shows event loop as the thread stack.
  - I hope I'm debugging the right issue, not a new one :laughing: 

So, it's still not clear, but I have some more places to debug.

**Comment by cccs-sgaron** [comment] 2024-01-17 14:28
That is interesting, I just recently added an APMAwareThreadPool executor. I might just switch service_server to use it so I can actually get an easy trace of execution for that code path.

In the meantime, you could switch the service that are hanging into privilege mode which they would bypass service_server and connect to the datastore directly.

**Comment by kam193** [comment] 2024-01-17 22:10
I can just stay with 88 for a while :) Anyway, the only thing I know for sure as of today, is that the code sometimes isn't going out of the [thread pool execution](https://github.com/CybercentreCanada/assemblyline-core/blob/74755b550a6bd00cba0c6c48d52fcd4063658a3d/assemblyline_core/tasking_client.py#L364-L367) context manager.  The clue with `save_or_freshen_file` seems not to be confirmed as occasionally, I see that it looks to be processed correctly when the issue occurs...

**Comment by kam193** [comment] 2024-01-18 20:59
To be honest, I'm quite lost with what's going on. I have also recognized that I started reproducing the issue on v88 without noticing it... So, I believe that I either found another issue, or just simulated what triggered it more often on v89 :smiling_face_with_tear: 

But I've found some interesting implications of using gevent workers I wasn't aware of, and a one quite similar issue.

1. Using gevent workers means, there is effectively no timeout on requests: https://github.com/benoitc/gunicorn/issues/2695 This explains why timeout on the client-side works, but the service server isn't killing connections. On the other hand, it also means, that configuring timeout on the client side is not a solution if we're not sure that replying them won't cause trouble - in case when the original request eventually finishes later.
2. Someone also has stuck requests when combining gevent with a ThreadPoolExecutor https://github.com/benoitc/gunicorn/issues/3117 However, they are getting an error from Gevent, what isn't our case.

So, without having any high confidence, I suspect it's a kind of issue in the combination Gevent+ThreadPoolExecutor+extensive external calls. I think that the v89 might have introduced some additional calls that increased the probability of this issue - and it happens only when you have many duplicates. Or it's unrelated :laughing:

**Comment by cccs-sgaron** [comment] 2024-01-18 21:08
@cccs-rs will do a best effort check to see what is going on. In the meantime, did you switch your services to be in privlege mode? 

We are also looking at porting Service Server to Rust in a near future so that issue will go away for sure then and Service Server should get a definite boost in performance.

**Comment by kam193** [comment] 2024-01-18 21:14
> In the meantime, did you switch your services to be in privlege mode?

No, I just downgraded my instance to v88 ;)

**Comment by kam193** [comment] 2024-01-18 21:15
Thank you for taking a look at this! Rust sounds interesting, I have to finally learn it :D

**Comment by cccs-rs** [comment] 2024-01-19 12:59
Upon testing with the particular file (thanks for providing a sample where we can reproduce the issue btw!), I was able to find that we don't cache file existence checks when handling the tasks which leads to unnecessary repetitive calls to the filestore (especially when we already know that file exists the first time around).

Now that being said, the issue is more obvious because of this sample but if you're dealing with several samples where within an archive there are multiple duplicate files that are extracted, then I can see where this would affect the performance of the system.

**Comment by cccs-rs** [comment] 2024-01-24 20:56
Should be resolved in the latest release. If the issue still persists, feel free to reopen the issue 😀

**Closed by cccs-rs** 2024-01-24 20:56 UTC
Labels: bug, accepted, assess, In progress

**Comment by kam193** [comment] 2024-01-26 15:35
Hi, I've upgraded my setup to v90 - unfortunately, the problem is still here. After some time, the service server apparently stops answering on some requests, and services are stuck waiting. It happens first on downloading a file, but later expands even to registering services - effectively preventing services from even trying to ask for a task.

However, the tip from @cccs-sgaron to run services in privileged mode seems to be working. This sounds to be a good temporary solution, but I'm still curious, what is going on in the Service Server

**Comment by cccs-sgaron** [comment] 2024-01-26 15:49
@cccs-rs did fix an infinite reconnection loop in this patch that we thought was causing your issue. @cccs-rs did that patch made it to the last release?
