### ISSUE TITLE
Server returns HTTP 500 when adding new badlist tag

### ISSUE THREAD

**Issue by jasper-vdhoven** [CybercentreCanada/assemblyline#280] opened 2024-10-25 11:37 UTC
**Describe the bug**
When creating a new badlist tag through the Assemblyline UI, the server returns an HTTP 500 error.

**To Reproduce**
1. Go to `Manage` -> `Badlist`
2. Click on `Add an item to the badlist`
3. Select `network.dynamic.domain` as the tag type, `foo.bar` as the tag value and `lorem ipsum` as the _Item Details_
4. Save the tag and the server responds with an HTTP 500 error

**Expected behavior**
In previous versions of AL this would successfully add a tag to the badlist. This feature still works when creating a new tag from an existing submission, it only appears when creating a new badlist item from scratch.

**Screenshots**
![image](https://github.com/user-attachments/assets/aef82e34-2d50-4a4d-97d0-3337290b65f3)

![image](https://github.com/user-attachments/assets/c3d0e8d8-4ab1-4758-9625-ff60b865142c)

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: `4.5.0.56`
 - Browser: Arc `Version 1.66.0 (55166) - Chromium Engine Version 130.0.6723.70`

**Comment by cccs-rs** [comment] 2024-10-25 11:56
Looks like a bug on the frontend side where the classification isn't being passed forward to the API (and the classification is required for adding an item), you can check the Payload tab to confirm but that's what I'm currently seeing our test system.

**Comment by jasper-vdhoven** [comment] 2024-10-29 07:36
Yeah, that is what I'm seeing as well, the `classification` element is an empty string (i.e. `""`), similar to the `id` value. Is this `id` value also not meant to be empty?

**Comment by cccs-rs** [comment] 2024-10-29 13:21
I believe for adding things to the list, having the `id` unset is fine because the system has to generate an identifier based on the information of the item.

**Comment by kam193** [comment] 2024-10-30 18:48
Could it be that it had a similar root cause as #273 ?

**Comment by cccs-rs** [comment] 2024-10-30 18:52
Possibly but not entirely sure.

**Comment by cccs-rs** [comment] 2024-11-29 20:39
This should be resolved in the [4.5.0.61](https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.5.0.stable61) release.

**Closed by cccs-rs** 2024-11-29 20:39 UTC
Labels: bug, core, ui-frontend, accepted, In progress
